### ISSUE TITLE
feat: 增加选股回测

### ISSUE THREAD

**Issue by bryantbyr** [bryantbyr/quant#2]
该模块为用户提供选股回测功能，以测试选股模型和策略的有效性。

1. 选定股票收益预测模型，设置回测参数，比如起始时间、结束时间、调仓频率、股票持有数目等。
2. 在选定的时间轴进行回测，记录收益情况，绘制累计收益率曲线，可选择基准对比；并给出回测的主要风险指标。

**Comment by coding-nobody** [comment]
Finished
