### ISSUE TITLE
feat: 系统管理员管理界面

### ISSUE THREAD

**Issue by bryantbyr** [bryantbyr/quant#3]
系统管理员登录系统
1. 系统管理
2. 用户管理

**Comment by coding-nobody** [comment]
1. 系统管理功能
1.1 因子增加，删除，信息编辑（含义）
1.2 可以增加新的选股模型，删除旧有模型

2. 普调用户管理功能
2.1 用户信息编辑
2.2 禁用、解禁某些账号
